version: '3.8'

# Production overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

services:
  khmer-ocr:
    build:
      context: .
      dockerfile: docker/Dockerfile.gpu
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '4'
        reservations:
          memory: 2G
          cpus: '2'
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - SERVICE_VARIANT=${SERVICE_VARIANT:-onnx}  # Use ONNX in production
      - USE_GPU=true
      - WORKERS=4
      - LOG_LEVEL=warning
      - MAX_REQUEST_SIZE=50M
      - REQUEST_TIMEOUT=30
    volumes:
      - ./models:/app/models:ro,cached
      - ./lang:/app/lang:ro,cached
      - ocr-logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
    depends_on:
      - khmer-ocr
    networks:
      - ocr-network
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - ocr-network
    restart: always

volumes:
  redis-data: