# Professional DBNet Detection config for HuggingFace datasets
# Optimized for RTX 3090 (24GB) training in Docker
model_type: dbnet
backbone: resnet50  # Better accuracy than mobilenet
image_size: [736, 736]  # Reduced from 960 for memory

optimizer:
  name: AdamW
  lr: 0.001
  weight_decay: 0.01
  scheduler:
    name: CosineAnnealingLR
    T_max: 30

train:
  epochs: 30
  batch_size: 16  # Optimized for RTX 3090
  amp: true  # Mixed precision
  seed: 42
  eval_steps: 200
  save_steps: 500
  gradient_accumulation: 2  # Effective batch = 32
  
data:
  train_list: data/paddle_format/detection/train/label.txt
  val_list: data/paddle_format/detection/val/label.txt
  test_list: data/paddle_format/detection/test/label.txt
  format: paddleocr_det
  num_workers: 4
  
  # Enhanced augmentation for Khmer text detection
  augmentation:
    - type: RandomCrop
      prob: 0.4
    - type: RandomRotate
      degree: 15
    - type: ColorJitter
      brightness: 0.3
      contrast: 0.3
      saturation: 0.2
    - type: RandomPerspective
      prob: 0.2
    - type: GaussianBlur
      prob: 0.1
      
# DBNet specific parameters
dbnet:
  thresh: 0.3
  box_thresh: 0.6
  unclip_ratio: 1.5
  
# Evaluation metrics
metrics:
  - precision
  - recall
  - f1
  - iou
  
# Production gates
gates:
  min_precision: 0.90
  min_recall: 0.85
  min_f1: 0.87
  
output:
  save_dir: models/dbnet_khmer_pro